-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_external_file`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_external_file
-- *
-- * Metadata about files (to be) loaded from external sources
-- *
-- *******************************************************/
CREATE TABLE `civicrm_external_file` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ExternalFile ID',
  `file_id` int unsigned COMMENT 'FK to File',
  `source` varchar(255) NOT NULL COMMENT 'Source URI',
  `filename` varchar(255) NOT NULL COMMENT 'Filename in download URI',
  `extension` varchar(255) NOT NULL COMMENT 'The extension that added the file',
  `custom_data` text NULL COMMENT 'Optional additional data',
  `status` varchar(64) NOT NULL,
  `download_start_date` datetime,
  `download_try_count` int unsigned NOT NULL,
  `last_modified` varchar(255) COMMENT 'Date used in Last-Modified header',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_external_file_file_id`(file_id),
  CONSTRAINT FK_civicrm_external_file_file_id FOREIGN KEY (`file_id`) REFERENCES `civicrm_file`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
